#!/bin/bash
#Script build.sh replaces VERSION_PLACEHOLDER with current version while creating PKGBUILD.
pkgname=micsync
pkgver=VERSION_PLACEHOLDER
pkgrel=1
pkgdesc=""
arch=('any')
url=""
license=('GPL3')
depends=('rsync>=3.1.3' 'python')
makedepends=('python-setuptools')
source=('https://files.pythonhosted.org/packages/source/m/micsync-micdmy/micsync-micdmy-VERSION_PLACEHOLDER.tar.gz')

build() {
	python setup.py build
}

package() {
	python setup.py install --root="$pkgdir/" --optimize=1 --skip-build
}

