#!/bin/bash
#Script build.sh replaces VERSION_PLACEHOLDER with current version while creating PKGBUILD.
pkgname=micsync
pkgver=VERSION_PLACEHOLDER
pkgrel=1
pkgdesc="Local data synchronization tool based on rsync."
arch=('any')
url="https://github.com/micdmy"
license=('GPL3')
depends=('rsync>=3.1.3' 'python>=3.7')
makedepends=('python-setuptools' 'python-wheel' 'twine')
source=('https://files.pythonhosted.org/packages/source/m/micsync/micsync-VERSION_PLACEHOLDER.tar.gz')

build() {
	cd ${pkgname}-${pkgver}/
	echo '###PKGBUILD: START python setup.py build ###'
	python setup.py build
	echo '###PKGBUILD: END python setup.py build ###'
}

package() {
	cd ${pkgname}-${pkgver}/
	echo '###PKGBUILD: START python setup.py install --root="$pkgdir/" --optimize=1 --skip-build ###'
	python setup.py install --root="$pkgdir/" --optimize=1 --skip-build
	echo '###PKGBUILD: END python setup.py install --root="$pkgdir/" --optimize=1 --skip-build ###'
}

